### ISSUE TITLE
感谢能开源这个项目

### ISSUE THREAD

**Issue by zzzczh** [rainboat2/MIT6.824-Cplusplus#1]
感谢能开源这个项目，我想问一些项目相关的问题
1.lab4是不是尚未完成，后续还会继续推进吗？
2.现存的测试用例是否完全覆盖了6.824原来的用例？我看好像6.824的test文件更丰富一些。

**Comment by rainboat2** [comment]
1. 这段时间要同时准备找秋招和毕业论文，时间实在不够用了。lab4我已经有了一个整体设计思路，后续空闲下来之后会继续完成这些内容。
2. 也是时间问题，因为MIT6.248给出的测试用例编写起来较为麻烦，目前没有全部覆盖。后续会进行更详细的测试。如果有兴趣欢迎提供更多测试用例。
